config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root to: 'foods#index'
  resources :recipes do
    resources :recipe_foods
  end
  resources :foods
  resources :shopping_list, only: [:index]
  get 'public_recipes/index'

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new # guest user (not logged in)

    can :manage, Recipe, user_id: user.id
    can :manage, Food, user_id: user.id
    can :read, :all
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/food.rb
class Food < ApplicationRecord
  belongs_to :user

  validates :name, presence: true
  validates :measurement_unit, presence: true
  validates :price, presence: true
  validates :price, numericality: { only_integer: true }

  has_many :recipe_foods, dependent: :destroy
  has_many :recipes, through: :recipe_foods
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :user

  validates :name, presence: true
  validates :preparation_time, presence: true
  validates :cooking_time, presence: true
  validates :description, presence: true

  has_many :recipe_foods
  has_many :foods, through: :recipe_foods
end

app/models/recipe_food.rb
class RecipeFood < ApplicationRecord
  belongs_to :recipe
  belongs_to :food
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :recipes
  has_many :foods
  has_many :recipe_foods, through: :recipes
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :update_allowed_parameters, if: :devise_controller?

  protected

  def update_allowed_parameters
    devise_parameter_sanitizer.permit(:sign_up) do |u|
      u.permit(:name, :email, :password, :password_confirmation)
    end
    devise_parameter_sanitizer.permit(:account_update) do |u|
      u.permit(:name, :email, :password, :password_confirmation, :current_password)
    end
  end
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  def index
    @foods = Food.all
  end

  def show
    @food = Food.find(params[:id])
  end

  def new
    @food = Food.new
  end

  def create
    @food = Food.new(food_params)

    if @food.save
      redirect_to foods_path, notice: "food #{@food.name} was successfully created!"
    else
      redirect_to new_food_path, notice: 'food could not be created!'
    end
  end

  def destroy
    food = Food.find(params[:id])
    food.destroy!
    redirect_to foods_path, notice: "food #{food.name} deleted successfully!"
  end

  private

  def food_params
    params.require(:food).permit(:name, :user_id, :measurement_unit, :price)
  end
end

app/controllers/public_recipes_controller.rb
class PublicRecipesController < ApplicationController
  def index
    @recipes = Recipe.where(public: true).order(created_at: :desc).includes(:user)
  end
end

app/controllers/recipe_foods_controller.rb
class RecipeFoodsController < ApplicationController
  def new
    @recipe = Recipe.find(params[:recipe_id])
    @recipe_food = RecipeFood.new
    @foods = Food.all.select { |food| @recipe.foods.exclude?(food) }
  end

  def create
    @recipe = Recipe.find(params[:recipe_id])
    @recipe_food = RecipeFood.new(recipe_food_params)
    @recipe_food.recipe_id = @recipe.id

    if @recipe_food.save
      redirect_to recipe_path(@recipe_food.recipe_id), notice: 'Ingredient was added successfully!'
    else
      flash[:alert] = 'Failed creating ingredient'
      redirect_back(fallback_location: root_path)
    end
  end

  def edit
    @recipe_food = RecipeFood.find(params[:id])
    @foods = Food.all
  end

  def update
    recipe_food = RecipeFood.find(params[:id])

    if recipe_food.update(recipe_food_params)
      redirect_to recipe_path(recipe_food.recipe_id), notice: 'Ingredient was edited successfully!'
    else
      redirect_to recipe_path(recipe_food.recipe_id), alert: 'Error editing ingredient!'
    end
  end

  def destroy
    recipe_food = RecipeFood.find(params[:id])
    recipe_food.destroy

    redirect_to recipe_path(recipe_food.recipe_id), notice: 'Ingredient was deleted successfully!'
  end

  private

  def recipe_food_params
    params.require(:recipe_food).permit(:recipe_id, :food_id, :quantity)
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  def index
    @recipes = current_user.recipes
  end

  def show
    @recipe = Recipe.find(params[:id])
    @ingridients = RecipeFood.where(recipe_id: params[:id]).includes(:food)
  end

  def new
    @recipe = Recipe.new
  end

  def create
    @recipe = Recipe.new(recipe_params)

    if @recipe.save
      redirect_to recipe_path(@recipe.id), notice: 'recipe was successfully created!'
    else
      redirect_to new_recipe_path, notice: 'recipe could not be created!'
    end
  end

  def update
    recipe = Recipe.find(params[:id])
    recipe.update(public: !recipe.public)

    redirect_to recipe_path(recipe.id), notice: "The recipe is now #{recipe.public ? 'public' : 'private'}!"
  end

  def destroy
    recipe = Recipe.find(params[:id])
    recipe.destroy!
    redirect_to recipes_path, notice: "Recipe #{recipe.name} deleted successfully!"
  end

  private

  def recipe_params
    params.require(:recipe).permit(:name, :user_id, :preparation_time, :cooking_time, :description, :public)
  end
end

app/controllers/shopping_list_controller.rb
class ShoppingListController < ApplicationController
  def index
    @recipe_foods = current_user.recipe_foods.includes(:food)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/food_helper.rb
module FoodHelper
end

app/helpers/public_recipes_helper.rb
module PublicRecipesHelper
end

app/helpers/recipe_foods_helper.rb
module RecipeFoodsHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/foods/index.html.erb
<div class="container mx-auto">
  <% if @foods.length !=0 %>
    <h1 class="text-center m-4 py-4 text-5xl font-medium">My Foods</h1>
    <div class="text-center m-4">
      <% if current_user %>
        <%= link_to "Add new food", new_food_path, class: "bg-gray-800 hover:bg-gray-700 text-white font-bold py-2 px-4 rounded" %>
      <% end %>
    </div>
    <div class="flex flex-col">
      <div class="overflow-x-auto sm:-mx-6 lg:-mx-8">
        <div class="py-2 inline-block min-w-full sm:px-6 lg:px-8">
          <div class="overflow-hidden">
            <table class="min-w-full">
              <thead class="bg-white border-b">
                <tr>
                  <th scope="col" class="text-sm font-medium text-gray-900 px-6 py-4 text-left">
                    #
                  </th>
                  <th scope="col" class="text-sm font-medium text-gray-900 px-6 py-4 text-left">
                    Food
                  </th>
                  <th scope="col" class="text-sm font-medium text-gray-900 px-6 py-4 text-left">
                  Measurement Unit
                  </th>
                  <th scope="col" class="text-sm font-medium text-gray-900 px-6 py-4 text-left">
                  Unit Price
                  </th>
                  <th scope="col" class="text-sm font-medium text-gray-900 px-6 py-4 text-left">
                  Actions
                </th>
                </tr>
              </thead>
              <tbody>
              <% @foods.each do |food| %>
                <tr class="bg-white border-b transition duration-300 ease-in-out hover:bg-gray-100">
                  <td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900"><%=food.id%></td>
                  <td class="text-sm text-gray-900 font-light px-6 py-4 whitespace-nowrap">
                  <%=food.name%>
                  </td>
                  <td class="text-sm text-gray-900 font-light px-6 py-4 whitespace-nowrap">
                  <%=food.measurement_unit%>
                  </td>
                  <td class="text-sm text-gray-900 font-light px-6 py-4 whitespace-nowrap">
                  <%=food.price%>
                  </td>
                  <td class="text-sm text-gray-900 font-light px-6 py-4 whitespace-nowrap">
                  <%= button_to "Remove", food_path(food.id), method: :delete, class: 'bg-gray-800 hover:bg-gray-700 text-white font-bold py-2 px-4 rounded' if can? :destroy, food  %>
                    </td>
                </tr>
              <%end%>
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  <%else%>

    <h1 class="text-center m-4 text-2xl font-medium">There are no foods</h1>
    <div class="text-center m-4">
      <%= link_to "Add new food", new_food_path, class: "bg-gray-800 hover:bg-gray-700 text-white font-bold py-2 px-4 rounded" %>
    </div>

  <%end%>
</div>

app/views/foods/new.html.erb
<div class="container mx-auto flex justify-center">
  <div class="p-6 max-w-lg bg-white rounded-lg border border-gray-200 shadow-md dark:bg-gray-800 dark:border-gray-700 dark:hover:bg-gray-700 m-2">
    <h1 class="mb-8 text-4xl font-bold tracking-tight text-gray-900 dark:text-white text-center">Create a new food</h1>
    <%= form_with model: @food, html: { class: 'flex flex-col gap-4 items-start' } do |f| %>
      <%= f.hidden_field :user_id, value: current_user.id%>
      <%= f.text_field :name, placeholder: 'Food name' %>
      <%= f.text_field :measurement_unit, placeholder: 'Measurement Unit' %>
      <%= f.number_field :price, placeholder: 'price(dollars)' %>
    
      <%= f.submit "Create Food", class: 'bg-gray-800 hover:bg-gray-700 text-white font-bold py-2 px-4 rounded'%>
    <% end %>
  </div>
</div>

app/views/layouts/_navbar.html.erb
<nav class="shadow bg-gray-900">
    <div class="container px-6 py-3 mx-auto">
        <div class="flex flex-col md:flex-row md:justify-between md:items-center">
            <div class="flex items-center justify-between">
                <div class="flex items-center">
                    <%= link_to 'Recipe App',  root_path, class: "text-2xl font-bold transition-colors duration-200 transform text-white lg:text-3xl hover:text-gray-300" %>
                </div>

                <!-- Mobile menu button -->
                <div class="flex md:hidden">
                    <button type="button" class="text-gray-200 hover:text-gray-400 focus:outline-none focus:text-gray-400" aria-label="toggle menu">
                        <svg viewBox="0 0 24 24" class="w-6 h-6 fill-current">
                            <path fill-rule="evenodd" d="M4 5h16a1 1 0 0 1 0 2H4a1 1 0 1 1 0-2zm0 6h16a1 1 0 0 1 0 2H4a1 1 0 0 1 0-2zm0 6h16a1 1 0 0 1 0 2H4a1 1 0 0 1 0-2z"></path>
                        </svg>
                    </button>
                </div>
            </div>

            <!-- Mobile Menu open: "block", Menu closed: "hidden" -->
            <div class="items-center md:flex">
                <div class="flex flex-col mt-2 md:flex-row md:mt-0 md:mx-1">
                    <%= link_to 'Foods', root_path, class: "my-1 text-sm leading-5 transition-colors duration-200 transform text-gray-200 hover:text-blue-400 hover:underline md:mx-4 md:my-0" %>
                    <% if user_signed_in? %>
                        <%= link_to 'My recepies', recipes_path, class: "my-1 text-sm leading-5 transition-colors duration-200 transform text-gray-200 hover:text-blue-400 hover:underline md:mx-4 md:my-0" %>
                        <%= link_to 'Shoping list', shopping_list_index_path, class: "my-1 text-sm leading-5 transition-colors duration-200 transform text-gray-200 hover:text-blue-400 hover:underline md:mx-4 md:my-0" %>
                    <% end %>
                    <%= link_to 'Public Recipes', public_recipes_index_path, class: "my-1 text-sm leading-5 transition-colors duration-200 transform text-gray-200 hover:text-blue-400 hover:underline md:mx-4 md:my-0" %>
                </div>

                <div class="md:flex">
                <% if user_signed_in? %>
                    <div class="my-1 text-sm leading-5 transition-colors duration-200 transform text-gray-200 hover:text-blue-400 hover:underline md:mx-4 md:my-1" >User: <%= current_user.name %></div>
                    <%= button_to("Log Out", destroy_user_session_path, method: :delete, class: "my-1 text-sm leading-5 transition-colors duration-200 transform text-gray-200 hover:text-blue-400 hover:underline md:mx-4 md:my-0") %>
                <% else %>
                    <%= link_to "Sign in", user_session_path, class: "my-1 text-sm leading-5 transition-colors duration-200 transform text-gray-200 hover:text-blue-400 hover:underline md:mx-4 md:my-0" %>
                    <%= link_to "Sign up", new_user_registration_path, class: "my-1 text-sm leading-5 transition-colors duration-200 transform text-gray-200 hover:text-blue-400 hover:underline md:mx-4 md:my-0" %>
                <% end %>
                </div>
            </div>
    </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Recipeapp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://cdn.tailwindcss.com"></script>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
    <%= render partial: "layouts/navbar" %>
    <% if notice %>
      <p class="alert alert-success px-10 py-2 bg-green-300"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert alert-danger px-10 py-2 bg-red-300"><%= alert %></p>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/public_recipes/index.html.erb
<div class="container mx-auto">
    <h1 class="text-center m-4 py-4 text-5xl font-medium">Public Recipes</h1>
    <ul class="flex flex-col gap-4">
      <% @recipes.each do |recipe| %>
        <li class="block p-6 max-w-xlg bg-white rounded-lg border border-gray-200 shadow-md hover:bg-gray-100 dark:bg-gray-800 dark:border-gray-700 dark:hover:bg-gray-700 m-2">
          <%= link_to recipe_path(recipe.id), class: " grid grid-cols-2 gap-y-4 justify-items-center" do  %>
            <h3 class="text-3xl hover:opacity-60"><%= recipe.name %></h3>
            <h3>Total food items: <span class="font-bold"><%= recipe.foods.count %></span></h3>
            <h3>by <span class="font-bold text-xl"><%= recipe.user.name %></span></h3>
            <h3>Total price: <span class="font-bold"> $<%= recipe.recipe_foods.includes(:food).map {|r| r.food.price.to_i * r.quantity.to_i }.sum %></span></h3>
          <% end %>
        </li>
      <% end %>
    </ul>
</div>

app/views/recipe_foods/edit.html.erb
<div class="container mx-auto flex justify-center">
  <div class="p-6 max-w-lg bg-white rounded-lg border border-gray-200 shadow-md dark:bg-gray-800 dark:border-gray-700 dark:hover:bg-gray-700 m-2">
    <h1 class="font-bold text-4xl mb-10">Edit ingredient</h1>
    <%= form_with model: @recipe_food, url: recipe_recipe_food_path(recipe_id: @recipe_food.recipe_id, id: @recipe_food.id), html: { class: 'flex flex-col items-start gap-4' }, method: :put do |f| %>
      <%= f.hidden_field :id, value: @recipe_food.id %>
      <%= f.hidden_field :recipe_id, value: @recipe_food.recipe_id %>
      <%= f.select :food_id, @foods.map { |food| [food.name, food.id] }, {}, { class: "w-full max-w-sm p-2"} %>
      <%= f.number_field :quantity, placeholder: 'Quantity', min: 0, required: true, class: "w-full max-w-[100px] p-2" %>
      <%= f.submit "Add ingredient", class: 'bg-gray-800 hover:bg-gray-700 text-white font-bold py-2 px-4 rounded' %>
    <% end %>
  </div>
</div>

app/views/recipe_foods/new.html.erb
<div class="container mx-auto flex justify-center">
  <div class="p-6 max-w-lg bg-white rounded-lg border border-gray-200 shadow-md dark:bg-gray-800 dark:border-gray-700 dark:hover:bg-gray-700 m-2">
    <h1 class="font-bold text-4xl mb-10">Add ingredient for <%= @recipe.name %></h1>
    <% if @foods.present? %>
      <%= form_with model: @recipe_food, url: recipe_recipe_foods_path, html: { class: 'flex flex-col items-start gap-4' } do |f| %>
        <%= f.select :food_id, @foods.map { |food| [food.name, food.id] }, {}, { class: "w-full max-w-sm p-2"} %>
        <%= f.number_field :quantity, placeholder: 'Quantity', min: 0, required: true, class: "w-full max-w-[100px] p-2" %>
        <%= f.submit "Add ingredient", class: 'bg-gray-800 hover:bg-gray-700 text-white font-bold py-2 px-4 rounded' %>
      <% end %>
    <% else %>
      <h3 class="font-bold mb-10">No food available for <%= current_user.name %> head over to <%= link_to "foods page", foods_path, class: 'underline' %> to add new food</h3>
    <% end %>
  </div>
</div>

app/views/recipes/index.html.erb
<div class="container mx-auto">
  <% if @recipes.length !=0 %>
    <h1 class="text-center m-4 py-4 text-5xl font-medium">My recepies</h1>
    <div class="text-center m-4">
      <%= link_to "Add new recipe", new_recipe_path, class: "bg-gray-800 hover:bg-gray-700 text-white font-bold py-2 px-4 rounded" %>
    </div>

    <% @recipes.each do |recipe| %>
      <%= link_to recipe_path(recipe.id), id: recipe.id do %>
      <div class="block p-6 max-w-xlg bg-white rounded-lg border border-gray-200 shadow-md hover:bg-gray-100 dark:bg-gray-800 dark:border-gray-700 dark:hover:bg-gray-700 m-2">
        <div class="flex flex-col md:flex-row">
          <div class="flex-1 text-center">
            <h5 class="mb-4 text-2xl font-bold tracking-tight text-gray-900 dark:text-white">
              <%= recipe.name %>
            </h5>
            <%= button_to "Remove", recipe_path(recipe.id), method: :delete, class: 'bg-gray-800 hover:bg-gray-700 text-white font-bold py-2 px-4 rounded' if can? :destroy, recipe %>
          </div>
          <div class="flex-1 text-center">
            <p class="text-base text-gray-800 md:text-lg"><%= truncate recipe.description, length: 240 %></p>
          </div>
        </div>
      </div>
      <% end %>
    <% end %>
    <% else %>
      <h1 class="text-center m-4 text-2xl font-medium">There are no recipes</h1>
      <div class="text-center m-4">
        <%= link_to "Add new recipe", new_recipe_path, class: "bg-gray-800 hover:bg-gray-700 text-white font-bold py-2 px-4 rounded" %>
      </div>
    <% end %>

</div>

app/views/recipes/new.html.erb
<div class="container mx-auto flex justify-center">
  <div class="p-6 max-w-lg bg-white rounded-lg border border-gray-200 shadow-md dark:bg-gray-800 dark:border-gray-700 dark:hover:bg-gray-700 m-2">
    <h1 class="mb-8 text-4xl font-bold tracking-tight text-gray-900 dark:text-white text-center">Create a new recipe</h1>
    <%= form_with model: @recipe, html: { class: 'flex flex-col gap-4 items-start' } do |f| %>
      <%= f.hidden_field :user_id, value: current_user.id %>
      <%= f.text_field :name, placeholder: 'Recipe name' %>
      <%= f.number_field :preparation_time, placeholder: 'Preparation Time (minutes)' %>
      <%= f.number_field :cooking_time, placeholder: 'Cooking Time (minutes)' %>
      <%= f.text_area :description, placeholder: 'Description', size: '50x5'%>
      <div>
        <%= f.label :public, "Public" %>
        <%= f.check_box :public %>
      </div>
      <%= f.submit "Create recipe", class: 'bg-gray-800 hover:bg-gray-700 text-white font-bold py-2 px-4 rounded'%>
    <% end %>
  </div>
</div>

app/views/recipes/show.html.erb
<div class="container mx-auto m-3">
  <div class="block p-6 max-w-xlg bg-white rounded-lg border border-gray-200 shadow-md dark:bg-gray-800 dark:border-gray-700 dark:hover:bg-gray-700 m-2">
    <h5 class="mb-16 text-5xl font-bold tracking-tight text-gray-900 dark:text-white text-center"><%= @recipe.name %></h5>
    <div class="flex flex-col md:flex-row">
      <div class="flex-1 text-center">
        <h5 class="mb-4 text-2xl font-bold tracking-tight text-gray-900 dark:text-white">
          Preparation time: <%= @recipe.preparation_time %> minutes
        </h5>
        <h5 class="mb-4 text-2xl font-bold tracking-tight text-gray-900 dark:text-white">
          Cooking time: <%= @recipe.cooking_time %> minutes
        </h5>
      </div>
      <div class="flex-1 text-center">
        <h5 class="mb-4 text-2xl font-bold tracking-tight text-gray-900 dark:text-white">
          This recipe is <%= @recipe.public ? 'public' : 'Private' %>
        </h5>
        <% if can? :manage, @recipe %>
          <%= button_to "Make it #{@recipe.public ? 'private' : 'public'}", recipe_path(@recipe.id), class: 'bg-gray-800 hover:bg-gray-700 text-white font-bold py-2 px-4 rounded', method: :patch %>
        <% end %>
      </div>
    </div>
    <div class="text-center">
      <p class="mb-4 text-1xl font-bold tracking-tight text-gray-900 dark:text-white">
        Descrition: <%= @recipe.description %>
      </p>
    </div>
    <div class="flex flex-col md:flex-row py-4">
      <div class="flex-1 text-center py-4">
        <button class="bg-gray-800 hover:bg-gray-700 text-white font-bold py-2 px-4 rounded">
          Generate shopin list
        </button>
      </div>
      <div class="flex-1 text-center py-4">
        <% if can? :manage, @recipe %>
          <%= link_to "Add ingredient", new_recipe_recipe_food_path(@recipe.id), class: 'bg-gray-800 hover:bg-gray-700 text-white font-bold py-2 px-4 rounded' %>
        <% end %>
      </div>
    </div>
    <hr class="my-8">
    <div>
      <% if @ingridients.present? %>
        <table class="table-auto w-full text-left mb-10 text-white text-lg border-collapse border border-slate-400">
          <thead class="bg-gray-800">
            <tr class="h-10">
              <th class="p-1">Food</th>
              <th class="p-1">Quanity</th>
              <th class="p-1">Price</th>
              <th class="p-1">Value</th>
              <th class="p-1"></th>
              <th class="p-1"></th>
            </tr>
          </thead>
          <tbody class="bg-gray-100 text-gray-800 p-20">
            <% @ingridients.each do |ingredient| %>
              <tr class="h-10">
                <td class="p-1"><%= ingredient.food.name %></td>
                <td class="p-1"><%= ingredient.quantity %> <%= ingredient.food.measurement_unit %></td>
                <td class="p-1">$<%= ingredient.food.price %></td>
                <td class="p-1">$<%= ingredient.food.price * ingredient.quantity || 0 %></td>
                <td class="p-1">
                  <%= link_to "Modify", edit_recipe_recipe_food_path(recipe_id: @recipe.id, id: ingredient.id), class: 'underline' if can? :manage, @recipe %>
                </td>
                <td class="p-1">
                  <%= button_to "Delete", recipe_recipe_food_path(recipe_id: @recipe.id, id: ingredient.id), method: :delete, class: 'underline' if can? :manage, @recipe%>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
      <% end %>
    </div>
  </div>
</div>

app/views/shopping_list/index.html.erb
<h1 class="font-bold text-4xl mb-10 text-center">Shopping List for <%= current_user.name %></h1>
<div class="mb-10 text-center">
  <span class="text-2xl">
    Amount of food items to buy: <span class="font-bold"><%= @recipe_foods.length %></span>
  </span>
  <span class="text-2xl">
    Total value of food needed: <span class="font-bold">$<%= @recipe_foods.map {|r| r.food.price.to_i * r.quantity.to_i }.sum %></span>
  </span>
</div>
<table class="table-auto w-full max-w-xl mx-auto text-left mb-10 text-lg">
  <thead class="bg-gray-400">
    <tr class="h-10">
      <th class="p-4">Food</th>
      <th class="p-4">Quantity</th>
      <th class="p-4">Price</th>
      <th class="p-4">Amount</th>
    </tr>
  </thead>
  <tbody class="bg-gray-300 p-20">
    <% @recipe_foods.each do |r|%>
      <tr class="h-16">
        <td class="p-4"><%= r.food.name %></td>
        <td class="p-4"><%= r.quantity %> <%= r.food.measurement_unit %></td>
        <td class="p-4">$<%= r.food.price %></td>
        <td class="p-4">$<%= r.food.price.to_i * r.quantity.to_i %></td>
      </tr>
    <% end %>
  </tbody>
</table>